# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reminders_windows/settingsWin.ui'
#
# Created: Tue Apr 12 23:46:25 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_settingsWin(object):
    def setupUi(self, settingsWin):
        settingsWin.setObjectName(_fromUtf8("settingsWin"))
        settingsWin.resize(513, 558)
        settingsWin.setSizeIncrement(QtCore.QSize(0, 0))
        self.mouseCb = QtGui.QCheckBox(settingsWin)
        self.mouseCb.setGeometry(QtCore.QRect(260, 60, 241, 44))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mouseCb.sizePolicy().hasHeightForWidth())
        self.mouseCb.setSizePolicy(sizePolicy)
        self.mouseCb.setChecked(False)
        self.mouseCb.setObjectName(_fromUtf8("mouseCb"))
        self.keyboardCb = QtGui.QCheckBox(settingsWin)
        self.keyboardCb.setGeometry(QtCore.QRect(260, 10, 241, 44))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyboardCb.sizePolicy().hasHeightForWidth())
        self.keyboardCb.setSizePolicy(sizePolicy)
        self.keyboardCb.setChecked(False)
        self.keyboardCb.setObjectName(_fromUtf8("keyboardCb"))
        self.soundCb = QtGui.QCheckBox(settingsWin)
        self.soundCb.setEnabled(False)
        self.soundCb.setGeometry(QtCore.QRect(260, 110, 241, 44))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.soundCb.sizePolicy().hasHeightForWidth())
        self.soundCb.setSizePolicy(sizePolicy)
        self.soundCb.setChecked(False)
        self.soundCb.setObjectName(_fromUtf8("soundCb"))
        self.fullScreenCb = QtGui.QCheckBox(settingsWin)
        self.fullScreenCb.setEnabled(False)
        self.fullScreenCb.setGeometry(QtCore.QRect(260, 160, 241, 44))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fullScreenCb.sizePolicy().hasHeightForWidth())
        self.fullScreenCb.setSizePolicy(sizePolicy)
        self.fullScreenCb.setChecked(False)
        self.fullScreenCb.setObjectName(_fromUtf8("fullScreenCb"))
        self.boringTe = QtGui.QTimeEdit(settingsWin)
        self.boringTe.setGeometry(QtCore.QRect(10, 50, 81, 27))
        self.boringTe.setAlignment(QtCore.Qt.AlignCenter)
        self.boringTe.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.boringTe.setSpecialValueText(_fromUtf8(""))
        self.boringTe.setAccelerated(True)
        self.boringTe.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(1, 0, 0)))
        self.boringTe.setMaximumTime(QtCore.QTime(1, 0, 0))
        self.boringTe.setMinimumTime(QtCore.QTime(0, 0, 10))
        self.boringTe.setObjectName(_fromUtf8("boringTe"))
        self.boringLb = QtGui.QLabel(settingsWin)
        self.boringLb.setGeometry(QtCore.QRect(10, 10, 241, 34))
        self.boringLb.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.boringLb.setWordWrap(True)
        self.boringLb.setObjectName(_fromUtf8("boringLb"))
        self.remindTe = QtGui.QTimeEdit(settingsWin)
        self.remindTe.setGeometry(QtCore.QRect(10, 120, 81, 27))
        self.remindTe.setAlignment(QtCore.Qt.AlignCenter)
        self.remindTe.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.remindTe.setSpecialValueText(_fromUtf8(""))
        self.remindTe.setAccelerated(True)
        self.remindTe.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(1, 0, 0)))
        self.remindTe.setMaximumTime(QtCore.QTime(1, 0, 0))
        self.remindTe.setMinimumTime(QtCore.QTime(0, 0, 10))
        self.remindTe.setObjectName(_fromUtf8("remindTe"))
        self.remindLb = QtGui.QLabel(settingsWin)
        self.remindLb.setGeometry(QtCore.QRect(10, 80, 241, 34))
        self.remindLb.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.remindLb.setWordWrap(True)
        self.remindLb.setObjectName(_fromUtf8("remindLb"))
        self.continuouslyLb = QtGui.QLabel(settingsWin)
        self.continuouslyLb.setGeometry(QtCore.QRect(10, 150, 241, 34))
        self.continuouslyLb.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.continuouslyLb.setWordWrap(True)
        self.continuouslyLb.setObjectName(_fromUtf8("continuouslyLb"))
        self.continuouslyTe = QtGui.QTimeEdit(settingsWin)
        self.continuouslyTe.setGeometry(QtCore.QRect(10, 190, 81, 27))
        self.continuouslyTe.setAlignment(QtCore.Qt.AlignCenter)
        self.continuouslyTe.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.continuouslyTe.setSpecialValueText(_fromUtf8(""))
        self.continuouslyTe.setAccelerated(True)
        self.continuouslyTe.setTime(QtCore.QTime(0, 0, 10))
        self.continuouslyTe.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(1, 0, 0)))
        self.continuouslyTe.setMaximumTime(QtCore.QTime(1, 0, 0))
        self.continuouslyTe.setMinimumTime(QtCore.QTime(0, 0, 10))
        self.continuouslyTe.setObjectName(_fromUtf8("continuouslyTe"))
        self.standbyTe = QtGui.QTimeEdit(settingsWin)
        self.standbyTe.setGeometry(QtCore.QRect(10, 260, 81, 27))
        self.standbyTe.setAlignment(QtCore.Qt.AlignCenter)
        self.standbyTe.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.standbyTe.setSpecialValueText(_fromUtf8(""))
        self.standbyTe.setAccelerated(True)
        self.standbyTe.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(1, 0, 0)))
        self.standbyTe.setMaximumTime(QtCore.QTime(1, 0, 0))
        self.standbyTe.setMinimumTime(QtCore.QTime(0, 1, 0))
        self.standbyTe.setObjectName(_fromUtf8("standbyTe"))
        self.standbyLb = QtGui.QLabel(settingsWin)
        self.standbyLb.setGeometry(QtCore.QRect(10, 220, 241, 34))
        self.standbyLb.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.standbyLb.setWordWrap(True)
        self.standbyLb.setObjectName(_fromUtf8("standbyLb"))
        self.cpuCb = QtGui.QCheckBox(settingsWin)
        self.cpuCb.setEnabled(False)
        self.cpuCb.setGeometry(QtCore.QRect(10, 370, 241, 44))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpuCb.sizePolicy().hasHeightForWidth())
        self.cpuCb.setSizePolicy(sizePolicy)
        self.cpuCb.setChecked(False)
        self.cpuCb.setObjectName(_fromUtf8("cpuCb"))
        self.CPUprocSb = QtGui.QSpinBox(settingsWin)
        self.CPUprocSb.setEnabled(False)
        self.CPUprocSb.setGeometry(QtCore.QRect(10, 435, 60, 27))
        self.CPUprocSb.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.CPUprocSb.setAccelerated(True)
        self.CPUprocSb.setMinimum(5)
        self.CPUprocSb.setMaximum(100)
        self.CPUprocSb.setObjectName(_fromUtf8("CPUprocSb"))
        self.cpu1Lb = QtGui.QLabel(settingsWin)
        self.cpu1Lb.setEnabled(False)
        self.cpu1Lb.setGeometry(QtCore.QRect(10, 415, 241, 17))
        self.cpu1Lb.setObjectName(_fromUtf8("cpu1Lb"))
        self.cpu2Lb = QtGui.QLabel(settingsWin)
        self.cpu2Lb.setEnabled(False)
        self.cpu2Lb.setGeometry(QtCore.QRect(76, 440, 151, 17))
        self.cpu2Lb.setObjectName(_fromUtf8("cpu2Lb"))
        self.cpu3Lb = QtGui.QLabel(settingsWin)
        self.cpu3Lb.setEnabled(False)
        self.cpu3Lb.setGeometry(QtCore.QRect(10, 465, 241, 17))
        self.cpu3Lb.setObjectName(_fromUtf8("cpu3Lb"))
        self.CPUtimeTe = QtGui.QTimeEdit(settingsWin)
        self.CPUtimeTe.setEnabled(False)
        self.CPUtimeTe.setGeometry(QtCore.QRect(10, 485, 81, 27))
        self.CPUtimeTe.setAlignment(QtCore.Qt.AlignCenter)
        self.CPUtimeTe.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.CPUtimeTe.setSpecialValueText(_fromUtf8(""))
        self.CPUtimeTe.setAccelerated(True)
        self.CPUtimeTe.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 45, 59)))
        self.CPUtimeTe.setMaximumTime(QtCore.QTime(0, 45, 59))
        self.CPUtimeTe.setObjectName(_fromUtf8("CPUtimeTe"))
        self.cpu4Lb = QtGui.QLabel(settingsWin)
        self.cpu4Lb.setEnabled(False)
        self.cpu4Lb.setGeometry(QtCore.QRect(95, 490, 131, 17))
        self.cpu4Lb.setObjectName(_fromUtf8("cpu4Lb"))
        self.hdd4Lb = QtGui.QLabel(settingsWin)
        self.hdd4Lb.setEnabled(False)
        self.hdd4Lb.setGeometry(QtCore.QRect(345, 490, 131, 17))
        self.hdd4Lb.setObjectName(_fromUtf8("hdd4Lb"))
        self.HDDprocSb = QtGui.QSpinBox(settingsWin)
        self.HDDprocSb.setEnabled(False)
        self.HDDprocSb.setGeometry(QtCore.QRect(260, 435, 60, 27))
        self.HDDprocSb.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.HDDprocSb.setAccelerated(True)
        self.HDDprocSb.setMinimum(5)
        self.HDDprocSb.setMaximum(100)
        self.HDDprocSb.setObjectName(_fromUtf8("HDDprocSb"))
        self.hddCb = QtGui.QCheckBox(settingsWin)
        self.hddCb.setEnabled(False)
        self.hddCb.setGeometry(QtCore.QRect(260, 370, 241, 44))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hddCb.sizePolicy().hasHeightForWidth())
        self.hddCb.setSizePolicy(sizePolicy)
        self.hddCb.setChecked(False)
        self.hddCb.setObjectName(_fromUtf8("hddCb"))
        self.hdd1Lb = QtGui.QLabel(settingsWin)
        self.hdd1Lb.setEnabled(False)
        self.hdd1Lb.setGeometry(QtCore.QRect(260, 415, 241, 17))
        self.hdd1Lb.setObjectName(_fromUtf8("hdd1Lb"))
        self.hdd3Lb = QtGui.QLabel(settingsWin)
        self.hdd3Lb.setEnabled(False)
        self.hdd3Lb.setGeometry(QtCore.QRect(260, 465, 241, 17))
        self.hdd3Lb.setObjectName(_fromUtf8("hdd3Lb"))
        self.hdd2Lb = QtGui.QLabel(settingsWin)
        self.hdd2Lb.setEnabled(False)
        self.hdd2Lb.setGeometry(QtCore.QRect(326, 440, 151, 17))
        self.hdd2Lb.setObjectName(_fromUtf8("hdd2Lb"))
        self.HDDtimeTe = QtGui.QTimeEdit(settingsWin)
        self.HDDtimeTe.setEnabled(False)
        self.HDDtimeTe.setGeometry(QtCore.QRect(260, 485, 81, 27))
        self.HDDtimeTe.setAlignment(QtCore.Qt.AlignCenter)
        self.HDDtimeTe.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.HDDtimeTe.setSpecialValueText(_fromUtf8(""))
        self.HDDtimeTe.setAccelerated(True)
        self.HDDtimeTe.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 45, 59)))
        self.HDDtimeTe.setMaximumTime(QtCore.QTime(0, 45, 59))
        self.HDDtimeTe.setObjectName(_fromUtf8("HDDtimeTe"))
        self.notActiveLb = QtGui.QLabel(settingsWin)
        self.notActiveLb.setGeometry(QtCore.QRect(260, 250, 241, 17))
        self.notActiveLb.setObjectName(_fromUtf8("notActiveLb"))
        self.notActiveOutLb = QtGui.QLabel(settingsWin)
        self.notActiveOutLb.setGeometry(QtCore.QRect(260, 270, 241, 17))
        self.notActiveOutLb.setObjectName(_fromUtf8("notActiveOutLb"))
        self.bottomBb = QtGui.QDialogButtonBox(settingsWin)
        self.bottomBb.setGeometry(QtCore.QRect(10, 520, 491, 27))
        self.bottomBb.setAutoFillBackground(False)
        self.bottomBb.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Save)
        self.bottomBb.setCenterButtons(True)
        self.bottomBb.setObjectName(_fromUtf8("bottomBb"))
        self.autostartCb = QtGui.QCheckBox(settingsWin)
        self.autostartCb.setEnabled(True)
        self.autostartCb.setGeometry(QtCore.QRect(10, 320, 241, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autostartCb.sizePolicy().hasHeightForWidth())
        self.autostartCb.setSizePolicy(sizePolicy)
        self.autostartCb.setChecked(False)
        self.autostartCb.setObjectName(_fromUtf8("autostartCb"))

        self.retranslateUi(settingsWin)
        QtCore.QMetaObject.connectSlotsByName(settingsWin)
        settingsWin.setTabOrder(self.boringTe, self.remindTe)
        settingsWin.setTabOrder(self.remindTe, self.continuouslyTe)
        settingsWin.setTabOrder(self.continuouslyTe, self.standbyTe)
        settingsWin.setTabOrder(self.standbyTe, self.keyboardCb)
        settingsWin.setTabOrder(self.keyboardCb, self.mouseCb)
        settingsWin.setTabOrder(self.mouseCb, self.soundCb)
        settingsWin.setTabOrder(self.soundCb, self.fullScreenCb)
        settingsWin.setTabOrder(self.fullScreenCb, self.cpuCb)
        settingsWin.setTabOrder(self.cpuCb, self.autostartCb)
        settingsWin.setTabOrder(self.autostartCb, self.CPUprocSb)
        settingsWin.setTabOrder(self.CPUprocSb, self.CPUtimeTe)
        settingsWin.setTabOrder(self.CPUtimeTe, self.hddCb)
        settingsWin.setTabOrder(self.hddCb, self.HDDprocSb)
        settingsWin.setTabOrder(self.HDDprocSb, self.HDDtimeTe)
        settingsWin.setTabOrder(self.HDDtimeTe, self.bottomBb)

    def retranslateUi(self, settingsWin):
        settingsWin.setWindowTitle(_translate("settingsWin", "Settings", None))
        self.mouseCb.setText(_translate("settingsWin", "Track mouse", None))
        self.keyboardCb.setText(_translate("settingsWin", "Track keyboard", None))
        self.soundCb.setText(_translate("settingsWin", "Track sound", None))
        self.fullScreenCb.setText(_translate("settingsWin", "Track full screen windows", None))
        self.boringTe.setDisplayFormat(_translate("settingsWin", "mm.ss", None))
        self.boringLb.setText(_translate("settingsWin", "Time reminder get bored", None))
        self.remindTe.setDisplayFormat(_translate("settingsWin", "mm.ss", None))
        self.remindLb.setText(_translate("settingsWin", "Time to first remind", None))
        self.continuouslyLb.setText(_translate("settingsWin", "Time to continuously remind user", None))
        self.continuouslyTe.setDisplayFormat(_translate("settingsWin", "mm.ss", None))
        self.standbyTe.setDisplayFormat(_translate("settingsWin", "mm.ss", None))
        self.standbyLb.setText(_translate("settingsWin", "Time to put system to Stand By", None))
        self.cpuCb.setText(_translate("settingsWin", "Track CPU load", None))
        self.cpu1Lb.setText(_translate("settingsWin", "Load more than", None))
        self.cpu2Lb.setText(_translate("settingsWin", "%", None))
        self.cpu3Lb.setText(_translate("settingsWin", "during", None))
        self.CPUtimeTe.setDisplayFormat(_translate("settingsWin", "mm.ss", None))
        self.cpu4Lb.setText(_translate("settingsWin", "is activity", None))
        self.hdd4Lb.setText(_translate("settingsWin", "is activity", None))
        self.hddCb.setText(_translate("settingsWin", "Track HDD load", None))
        self.hdd1Lb.setText(_translate("settingsWin", "Load more than", None))
        self.hdd3Lb.setText(_translate("settingsWin", "during", None))
        self.hdd2Lb.setText(_translate("settingsWin", "%", None))
        self.HDDtimeTe.setDisplayFormat(_translate("settingsWin", "mm.ss", None))
        self.notActiveLb.setText(_translate("settingsWin", "Time not active", None))
        self.notActiveOutLb.setText(_translate("settingsWin", "0 min 0 s", None))
        self.autostartCb.setText(_translate("settingsWin", "Autostart", None))

